// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVSy3RBF-G6qhdkXGAwtJWg5oBLowE7gY',
    appId: '1:857659719697:web:3743f2bb8c505d121eb1b0',
    messagingSenderId: '857659719697',
    projectId: 'mvp-loco',
    authDomain: 'mvp-loco.firebaseapp.com',
    storageBucket: 'mvp-loco.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn0lbvcXBs_DumwqZQxsvnqBHhnb686iw',
    appId: '1:857659719697:android:fb76df888a9b5c9f1eb1b0',
    messagingSenderId: '857659719697',
    projectId: 'mvp-loco',
    storageBucket: 'mvp-loco.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW8-avb_KLIBl9VHngHgU3kUNAU8o-oGY',
    appId: '1:857659719697:ios:f779f325f2bf455d1eb1b0',
    messagingSenderId: '857659719697',
    projectId: 'mvp-loco',
    storageBucket: 'mvp-loco.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW8-avb_KLIBl9VHngHgU3kUNAU8o-oGY',
    appId: '1:857659719697:ios:f779f325f2bf455d1eb1b0',
    messagingSenderId: '857659719697',
    projectId: 'mvp-loco',
    storageBucket: 'mvp-loco.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
